import 'package:flutter/material.dart';

import 'shadcn_names.dart';
import 'shadcn_style_tokens.dart';

/// Registry for official shadcn style presets.
abstract final class ShadcnStyles {
  static const Map<ShadcnStyleName, ShadcnStyleTokens> all = {
    ShadcnStyleName.vega: ShadcnStyleTokens(
      name: ShadcnStyleName.vega,
      title: 'Vega',
      description: 'Clean, neutral, and familiar.',
      spacingUnit: 4,
      visualDensity: VisualDensity.standard,
      borderWidth: 1,
      focusRingWidth: 3,
      focusRingOpacity: 0.50,
      stateLayerOpacity: 0.08,
      buttonHeightXs: 24,
      buttonHeightSm: 32,
      buttonHeight: 36,
      buttonHeightLg: 40,
      buttonPaddingX: 10,
      buttonGap: 6,
      buttonRadius: 8,
      buttonFontSize: 14,
      buttonFontWeight: FontWeight.w500,
      buttonLetterSpacing: 0,
      uppercaseButtons: false,
      iconSize: 16,
      iconButtonSize: 36,
      inputHeight: 36,
      inputHeightSm: 32,
      inputPaddingX: 10,
      inputPaddingY: 4,
      inputRadius: 8,
      inputFontSize: 14,
      checkboxSize: 16,
      switchWidth: 32,
      switchHeight: 18.4,
      sliderThumbSize: 16,
      cardPadding: 24,
      cardPaddingSm: 16,
      cardGap: 24,
      cardRadius: 14,
      cardElevation: 1,
      dialogPadding: 24,
      dialogGap: 24,
      dialogRadius: 14,
      dialogElevation: 1,
      menuItemPaddingX: 16,
      menuItemPaddingY: 8,
      menuItemRadius: 8,
      text: _typographyRegular,
    ),
    ShadcnStyleName.nova: ShadcnStyleTokens(
      name: ShadcnStyleName.nova,
      title: 'Nova',
      description: 'Reduced padding and margins.',
      spacingUnit: 4,
      visualDensity: VisualDensity(horizontal: -1, vertical: -1),
      borderWidth: 1,
      focusRingWidth: 3,
      focusRingOpacity: 0.50,
      stateLayerOpacity: 0.08,
      buttonHeightXs: 24,
      buttonHeightSm: 28,
      buttonHeight: 32,
      buttonHeightLg: 36,
      buttonPaddingX: 10,
      buttonGap: 6,
      buttonRadius: 10,
      buttonFontSize: 14,
      buttonFontWeight: FontWeight.w500,
      buttonLetterSpacing: 0,
      uppercaseButtons: false,
      iconSize: 16,
      iconButtonSize: 32,
      inputHeight: 32,
      inputHeightSm: 28,
      inputPaddingX: 10,
      inputPaddingY: 4,
      inputRadius: 10,
      inputFontSize: 14,
      checkboxSize: 16,
      switchWidth: 32,
      switchHeight: 18.4,
      sliderThumbSize: 12,
      cardPadding: 16,
      cardPaddingSm: 12,
      cardGap: 16,
      cardRadius: 14,
      cardElevation: 0,
      dialogPadding: 16,
      dialogGap: 16,
      dialogRadius: 14,
      dialogElevation: 0,
      menuItemPaddingX: 10,
      menuItemPaddingY: 6,
      menuItemRadius: 10,
      text: _typographyRegular,
    ),
    ShadcnStyleName.maia: ShadcnStyleTokens(
      name: ShadcnStyleName.maia,
      title: 'Maia',
      description: 'Rounded, with generous spacing.',
      spacingUnit: 4,
      visualDensity: VisualDensity.comfortable,
      borderWidth: 1,
      focusRingWidth: 3,
      focusRingOpacity: 0.50,
      stateLayerOpacity: 0.08,
      buttonHeightXs: 24,
      buttonHeightSm: 32,
      buttonHeight: 36,
      buttonHeightLg: 40,
      buttonPaddingX: 12,
      buttonGap: 6,
      buttonRadius: 26,
      buttonFontSize: 14,
      buttonFontWeight: FontWeight.w500,
      buttonLetterSpacing: 0,
      uppercaseButtons: false,
      iconSize: 16,
      iconButtonSize: 36,
      inputHeight: 36,
      inputHeightSm: 32,
      inputPaddingX: 12,
      inputPaddingY: 4,
      inputRadius: 26,
      inputFontSize: 14,
      checkboxSize: 16,
      switchWidth: 32,
      switchHeight: 18.4,
      sliderThumbSize: 16,
      cardPadding: 24,
      cardPaddingSm: 16,
      cardGap: 24,
      cardRadius: 18,
      cardElevation: 1,
      dialogPadding: 24,
      dialogGap: 24,
      dialogRadius: 18,
      dialogElevation: 1,
      menuItemPaddingX: 12,
      menuItemPaddingY: 8,
      menuItemRadius: 10,
      text: _typographyRegular,
    ),
    ShadcnStyleName.lyra: ShadcnStyleTokens(
      name: ShadcnStyleName.lyra,
      title: 'Lyra',
      description: 'Boxy and sharp. For mono fonts.',
      spacingUnit: 4,
      visualDensity: VisualDensity(horizontal: -1, vertical: -1),
      borderWidth: 1,
      focusRingWidth: 1,
      focusRingOpacity: 0.50,
      stateLayerOpacity: 0.08,
      buttonHeightXs: 24,
      buttonHeightSm: 28,
      buttonHeight: 32,
      buttonHeightLg: 36,
      buttonPaddingX: 10,
      buttonGap: 6,
      buttonRadius: 0,
      buttonFontSize: 12,
      buttonFontWeight: FontWeight.w500,
      buttonLetterSpacing: 0,
      uppercaseButtons: false,
      iconSize: 16,
      iconButtonSize: 32,
      inputHeight: 32,
      inputHeightSm: 28,
      inputPaddingX: 10,
      inputPaddingY: 4,
      inputRadius: 0,
      inputFontSize: 12,
      checkboxSize: 16,
      switchWidth: 32,
      switchHeight: 18.4,
      sliderThumbSize: 16,
      cardPadding: 16,
      cardPaddingSm: 12,
      cardGap: 16,
      cardRadius: 0,
      cardElevation: 0,
      dialogPadding: 16,
      dialogGap: 16,
      dialogRadius: 0,
      dialogElevation: 0,
      menuItemPaddingX: 10,
      menuItemPaddingY: 6,
      menuItemRadius: 0,
      text: _typographyCompact,
    ),
    ShadcnStyleName.mira: ShadcnStyleTokens(
      name: ShadcnStyleName.mira,
      title: 'Mira',
      description: 'Made for compact interfaces.',
      spacingUnit: 4,
      visualDensity: VisualDensity.compact,
      borderWidth: 1,
      focusRingWidth: 2,
      focusRingOpacity: 0.30,
      stateLayerOpacity: 0.08,
      buttonHeightXs: 20,
      buttonHeightSm: 24,
      buttonHeight: 28,
      buttonHeightLg: 32,
      buttonPaddingX: 8,
      buttonGap: 4,
      buttonRadius: 8,
      buttonFontSize: 12,
      buttonFontWeight: FontWeight.w500,
      buttonLetterSpacing: 0,
      uppercaseButtons: false,
      iconSize: 14,
      iconButtonSize: 28,
      inputHeight: 28,
      inputHeightSm: 24,
      inputPaddingX: 8,
      inputPaddingY: 2,
      inputRadius: 8,
      inputFontSize: 12,
      checkboxSize: 16,
      switchWidth: 28,
      switchHeight: 16.6,
      sliderThumbSize: 12,
      cardPadding: 16,
      cardPaddingSm: 12,
      cardGap: 16,
      cardRadius: 10,
      cardElevation: 0,
      dialogPadding: 16,
      dialogGap: 16,
      dialogRadius: 10,
      dialogElevation: 0,
      menuItemPaddingX: 8,
      menuItemPaddingY: 6,
      menuItemRadius: 8,
      text: _typographyCompact,
    ),
    ShadcnStyleName.luma: ShadcnStyleTokens(
      name: ShadcnStyleName.luma,
      title: 'Luma',
      description: 'Fluid, luminous, and soft.',
      spacingUnit: 4,
      visualDensity: VisualDensity.comfortable,
      borderWidth: 1,
      focusRingWidth: 3,
      focusRingOpacity: 0.30,
      stateLayerOpacity: 0.10,
      buttonHeightXs: 24,
      buttonHeightSm: 32,
      buttonHeight: 36,
      buttonHeightLg: 40,
      buttonPaddingX: 12,
      buttonGap: 6,
      buttonRadius: 26,
      buttonFontSize: 14,
      buttonFontWeight: FontWeight.w500,
      buttonLetterSpacing: 0,
      uppercaseButtons: false,
      iconSize: 16,
      iconButtonSize: 36,
      inputHeight: 36,
      inputHeightSm: 32,
      inputPaddingX: 12,
      inputPaddingY: 4,
      inputRadius: 22,
      inputFontSize: 14,
      checkboxSize: 16,
      switchWidth: 44,
      switchHeight: 20,
      sliderThumbSize: 24,
      cardPadding: 24,
      cardPaddingSm: 16,
      cardGap: 24,
      cardRadius: 26,
      cardElevation: 2,
      dialogPadding: 24,
      dialogGap: 24,
      dialogRadius: 26,
      dialogElevation: 2,
      menuItemPaddingX: 18,
      menuItemPaddingY: 10,
      menuItemRadius: 22,
      text: _typographyRegular,
    ),
    ShadcnStyleName.sera: ShadcnStyleTokens(
      name: ShadcnStyleName.sera,
      title: 'Sera',
      description: 'Editorial and typographic.',
      spacingUnit: 4,
      visualDensity: VisualDensity.standard,
      borderWidth: 1,
      focusRingWidth: 2,
      focusRingOpacity: 0.30,
      stateLayerOpacity: 0.08,
      buttonHeightXs: 24,
      buttonHeightSm: 32,
      buttonHeight: 36,
      buttonHeightLg: 40,
      buttonPaddingX: 18,
      buttonGap: 6,
      buttonRadius: 0,
      buttonFontSize: 12,
      buttonFontWeight: FontWeight.w600,
      buttonLetterSpacing: 1.6,
      uppercaseButtons: true,
      iconSize: 14,
      iconButtonSize: 36,
      inputHeight: 40,
      inputHeightSm: 36,
      inputPaddingX: 0,
      inputPaddingY: 4,
      inputRadius: 0,
      inputFontSize: 14,
      checkboxSize: 18,
      switchWidth: 33,
      switchHeight: 18,
      sliderThumbSize: 12,
      cardPadding: 24,
      cardPaddingSm: 16,
      cardGap: 24,
      cardRadius: 0,
      cardElevation: 2,
      dialogPadding: 24,
      dialogGap: 24,
      dialogRadius: 0,
      dialogElevation: 2,
      menuItemPaddingX: 18,
      menuItemPaddingY: 10,
      menuItemRadius: 0,
      text: _typographyEditorial,
    ),
  };

  static ShadcnStyleTokens get(ShadcnStyleName name) => all[name]!;

  static Iterable<ShadcnStyleTokens> get values => all.values;
}

extension ShadcnStyleNameTokens on ShadcnStyleName {
  ShadcnStyleTokens get tokens => ShadcnStyles.get(this);
}

const _typographyRegular = ShadcnTypographyTokens(
  displayLarge: ShadcnTextStyleToken(
    fontSize: 48,
    lineHeight: 56,
    fontWeight: FontWeight.w600,
  ),
  displayMedium: ShadcnTextStyleToken(
    fontSize: 40,
    lineHeight: 48,
    fontWeight: FontWeight.w600,
  ),
  displaySmall: ShadcnTextStyleToken(
    fontSize: 32,
    lineHeight: 40,
    fontWeight: FontWeight.w600,
  ),
  headlineLarge: ShadcnTextStyleToken(
    fontSize: 28,
    lineHeight: 36,
    fontWeight: FontWeight.w600,
  ),
  headlineMedium: ShadcnTextStyleToken(
    fontSize: 24,
    lineHeight: 32,
    fontWeight: FontWeight.w600,
  ),
  headlineSmall: ShadcnTextStyleToken(
    fontSize: 20,
    lineHeight: 28,
    fontWeight: FontWeight.w600,
  ),
  titleLarge: ShadcnTextStyleToken(
    fontSize: 18,
    lineHeight: 28,
    fontWeight: FontWeight.w600,
  ),
  titleMedium: ShadcnTextStyleToken(
    fontSize: 16,
    lineHeight: 24,
    fontWeight: FontWeight.w500,
  ),
  titleSmall: ShadcnTextStyleToken(
    fontSize: 14,
    lineHeight: 20,
    fontWeight: FontWeight.w500,
  ),
  bodyLarge: ShadcnTextStyleToken(
    fontSize: 16,
    lineHeight: 24,
    fontWeight: FontWeight.w400,
  ),
  bodyMedium: ShadcnTextStyleToken(
    fontSize: 14,
    lineHeight: 20,
    fontWeight: FontWeight.w400,
  ),
  bodySmall: ShadcnTextStyleToken(
    fontSize: 12,
    lineHeight: 16,
    fontWeight: FontWeight.w400,
  ),
  labelLarge: ShadcnTextStyleToken(
    fontSize: 14,
    lineHeight: 20,
    fontWeight: FontWeight.w500,
  ),
  labelMedium: ShadcnTextStyleToken(
    fontSize: 12,
    lineHeight: 16,
    fontWeight: FontWeight.w500,
  ),
  labelSmall: ShadcnTextStyleToken(
    fontSize: 11,
    lineHeight: 16,
    fontWeight: FontWeight.w500,
  ),
);

const _typographyCompact = ShadcnTypographyTokens(
  displayLarge: ShadcnTextStyleToken(
    fontSize: 40,
    lineHeight: 48,
    fontWeight: FontWeight.w600,
  ),
  displayMedium: ShadcnTextStyleToken(
    fontSize: 34,
    lineHeight: 40,
    fontWeight: FontWeight.w600,
  ),
  displaySmall: ShadcnTextStyleToken(
    fontSize: 28,
    lineHeight: 34,
    fontWeight: FontWeight.w600,
  ),
  headlineLarge: ShadcnTextStyleToken(
    fontSize: 24,
    lineHeight: 32,
    fontWeight: FontWeight.w600,
  ),
  headlineMedium: ShadcnTextStyleToken(
    fontSize: 20,
    lineHeight: 28,
    fontWeight: FontWeight.w600,
  ),
  headlineSmall: ShadcnTextStyleToken(
    fontSize: 16,
    lineHeight: 24,
    fontWeight: FontWeight.w600,
  ),
  titleLarge: ShadcnTextStyleToken(
    fontSize: 16,
    lineHeight: 24,
    fontWeight: FontWeight.w600,
  ),
  titleMedium: ShadcnTextStyleToken(
    fontSize: 14,
    lineHeight: 20,
    fontWeight: FontWeight.w500,
  ),
  titleSmall: ShadcnTextStyleToken(
    fontSize: 12,
    lineHeight: 18,
    fontWeight: FontWeight.w500,
  ),
  bodyLarge: ShadcnTextStyleToken(
    fontSize: 14,
    lineHeight: 22,
    fontWeight: FontWeight.w400,
  ),
  bodyMedium: ShadcnTextStyleToken(
    fontSize: 12,
    lineHeight: 18,
    fontWeight: FontWeight.w400,
  ),
  bodySmall: ShadcnTextStyleToken(
    fontSize: 11,
    lineHeight: 16,
    fontWeight: FontWeight.w400,
  ),
  labelLarge: ShadcnTextStyleToken(
    fontSize: 12,
    lineHeight: 18,
    fontWeight: FontWeight.w500,
  ),
  labelMedium: ShadcnTextStyleToken(
    fontSize: 11,
    lineHeight: 16,
    fontWeight: FontWeight.w500,
  ),
  labelSmall: ShadcnTextStyleToken(
    fontSize: 10,
    lineHeight: 14,
    fontWeight: FontWeight.w500,
  ),
);

const _typographyEditorial = ShadcnTypographyTokens(
  displayLarge: ShadcnTextStyleToken(
    fontSize: 52,
    lineHeight: 60,
    fontWeight: FontWeight.w600,
  ),
  displayMedium: ShadcnTextStyleToken(
    fontSize: 44,
    lineHeight: 52,
    fontWeight: FontWeight.w600,
  ),
  displaySmall: ShadcnTextStyleToken(
    fontSize: 34,
    lineHeight: 42,
    fontWeight: FontWeight.w600,
  ),
  headlineLarge: ShadcnTextStyleToken(
    fontSize: 30,
    lineHeight: 38,
    fontWeight: FontWeight.w600,
  ),
  headlineMedium: ShadcnTextStyleToken(
    fontSize: 24,
    lineHeight: 34,
    fontWeight: FontWeight.w600,
  ),
  headlineSmall: ShadcnTextStyleToken(
    fontSize: 20,
    lineHeight: 30,
    fontWeight: FontWeight.w600,
  ),
  titleLarge: ShadcnTextStyleToken(
    fontSize: 18,
    lineHeight: 28,
    fontWeight: FontWeight.w600,
  ),
  titleMedium: ShadcnTextStyleToken(
    fontSize: 14,
    lineHeight: 22,
    fontWeight: FontWeight.w600,
    letterSpacing: 0.8,
  ),
  titleSmall: ShadcnTextStyleToken(
    fontSize: 12,
    lineHeight: 18,
    fontWeight: FontWeight.w600,
    letterSpacing: 1.0,
  ),
  bodyLarge: ShadcnTextStyleToken(
    fontSize: 16,
    lineHeight: 26,
    fontWeight: FontWeight.w400,
  ),
  bodyMedium: ShadcnTextStyleToken(
    fontSize: 14,
    lineHeight: 24,
    fontWeight: FontWeight.w400,
  ),
  bodySmall: ShadcnTextStyleToken(
    fontSize: 12,
    lineHeight: 18,
    fontWeight: FontWeight.w400,
  ),
  labelLarge: ShadcnTextStyleToken(
    fontSize: 12,
    lineHeight: 18,
    fontWeight: FontWeight.w600,
    letterSpacing: 1.6,
  ),
  labelMedium: ShadcnTextStyleToken(
    fontSize: 11,
    lineHeight: 16,
    fontWeight: FontWeight.w600,
    letterSpacing: 1.4,
  ),
  labelSmall: ShadcnTextStyleToken(
    fontSize: 10,
    lineHeight: 14,
    fontWeight: FontWeight.w600,
    letterSpacing: 1.2,
  ),
);
